default_profile = "nitrochat"

[profiles.nitrochat]
user_id = "@ash:nitro.chat"

[settings]
image_preview = {}

[settings.notifications]
enabled = true

# Keybindings

[macros.normal]
";" = ":"
"gc" = ":chats<Enter>"

[macros.insert]
"<C-Enter>" = "<Esc><Enter>"
"<Enter>" = "<S-Enter>"
